In [1]:
import numpy as np

# Python list
py_list = [1, 2, 3, 4, 5]

# Convert to NumPy array
np_array = np.array(py_list)

print(np_array)  # Output: [1 2 3 4 5]


[1 2 3 4 5]


In [3]:
import numpy as np

# Create an array filled with zeros
zeros_array = np.zeros((3, 4))  # Shape (3, 4)

print(zeros_array)
# Output:
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
import numpy as np

# Create an array filled with ones
ones_array = np.ones((2, 3))  # Shape (2, 3)

print(ones_array)
# Output:
# [[1. 1. 1.]
#  [1. 1. 1.]]


[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
import numpy as np

# Create an array with a range of values
range_array = np.arange(10)  # Range from 0 to 9

print(range_array)  # Output: [0 1 2 3 4 5 6 7 8 9]


[0 1 2 3 4 5 6 7 8 9]


In [9]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
import numpy as np

# Create an array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Find the shape
shape = array.shape

print(shape)  # Output: (2, 3)


(2, 3)


In [13]:
import numpy as np

# Create an array
array = np.arange(12)

# Reshape the array
reshaped_array = array.reshape((3, 4))

print(reshaped_array)
# Output:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_array = array[::-1]

print(reversed_array)  # Output: [5 4 3 2 1]


[5 4 3 2 1]


In [17]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenate the arrays
concatenated_array = np.concatenate((array1, array2))

print(concatenated_array)  # Output: [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [19]:
import numpy as np

# Create an array
array = np.array([1, 3, 5, 7, 9])

# Find the maximum value
max_value = np.max(array)

print(max_value)  # Output: 9


9


In [21]:
import numpy as np

# Create an array
array = np.array([1, 3, 5, 7, 9])

# Find the minimum value
min_value = np.min(array)

print(min_value)  # Output: 1


1


In [23]:
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5])

# Find the mean
mean_value = np.mean(array)

print(mean_value)  # Output: 3.0


3.0


In [25]:
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5])

# Find the standard deviation
std_dev = np.std(array)

print(std_dev)  # Output: 1.4142135623730951


1.4142135623730951


In [27]:
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5])

# Find the sum
sum_value = np.sum(array)

print(sum_value)  # Output: 15


15


In [29]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array_1d)
print(array_2d)
print(array_3d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Perform element-wise addition
sum_array = array1 + array2

print(sum_array)  # Output: [5 7 9]


[5 7 9]


In [33]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Perform element-wise multiplication
product_array = array1 * array2

print(product_array)  # Output: [ 4 10 18]


[ 4 10 18]


In [35]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
matrix_product = np.dot(matrix1, matrix2)

print(matrix_product)
# Output:
# [[19 22]
#  [43 50]]


[[19 22]
 [43 50]]


In [37]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the array
transposed_array = np.transpose(array)

print(transposed_array)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]


[[1 4]
 [2 5]
 [3 6]]


In [39]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

# Compute the inverse
inverse_matrix = np.linalg.inv(matrix)

print(inverse_matrix)
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]


[[-2.   1. ]
 [ 1.5 -0.5]]


In [41]:
import numpy as np

# Create an array
array = np.array([3, 1, 4, 1, 5, 9])

# Sort the array
sorted_array = np.sort(array)

print(sorted_array)  # Output: [1 1 3 4 5 9]


[1 1 3 4 5 9]


In [43]:
import numpy as np

# Generate random numbers between 0 and 1
random_numbers = np.random.rand(5)

# Generate random integers between 0 and 10
random_integers = np.random.randint(0, 10, size=5)

print(random_numbers)
print(random_integers)


[0.17700163 0.85246157 0.14925497 0.10169361 0.99478676]
[7 7 9 7 0]
